### ISSUE TITLE
Invalid libva driver for linux OS

### ISSUE THREAD

**Issue by TechPenguineer** [ZenoINC/Zeno-IDE#21]
**Full Error**
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[13746:0909/184727.682045:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```
OS: Linux
Distro: Ubuntu

**Comment by mientje** [comment]
This issue is closed but I have the exact same message and I don't know what to do. My electron app won't start.
Thank you and greets, Karin Meersman

**Comment by TechPenguineer** [comment]
> This issue is closed but I have the exact same message and I don't know what to do. My electron app won't start. Thank you and greets, Karin Meersman

Hello There Karin! Although this project has since been abandoned to fix this issue you can reinstall the electron framework via npm. This is commonly due to the usage of an older version of Electron.
